openapi: "3.0.0"
paths:
  /stocks:
    get:
      summary: Get stocks prices on real time
      operationId: listPrices
      tags:
        - stocks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Stock:
      type: object
      required:
        - id
        - name
        - symbol
        - currentPrice
        - lastUpdated
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        symbol:
          type: string
        currentPrice:
          type: number
        lastUpdated:
          type: number
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
info:
  title: stock finance reactive app
  description: for KPI reactive course
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
